### ISSUE TITLE
Expected FPS?

### ISSUE THREAD

**Issue by gkahn13** [carla-simulator/carla#10] opened 2017-11-07 07:58 UTC
I am trying to see how fast I can get CARLA to run with minimal settings. For only receiving small images, I can get about 10 fps, which is a bit slower than real-time. Is this the expected speed? Details to reproduce are below.

Server:
```
./CarlaUE4.sh /Game/Maps/Town01 -benchmark -fps=15 -carla-no-hud
```

Client:
```
$ python carla_example.py localhost 2000
```

CarlaSettings.ini
```
[CARLA/Server]
UseNetworking=true
SynchronousMode = true
SendNonPlayerAgentsInfo= false

[CARLA/LevelSettings]
NumberOfVehicles=10
NumberOfPedestrians=10
WeatherId=1

[CARLA/SceneCapture]
Cameras=RGB
ImageSizeX=160
ImageSizeY=120
CameraFOV=100
CameraPositionX=200
CameraPositionY=0
CameraPositionZ=140
CameraRotationPitch=-15.0
CameraRotationRoll=0
CameraRotationYaw=0


[CARLA/SceneCapture/RGB]
PostProcessing=SceneFinal
CameraPositionY=0
CameraRotationYaw=0
```

Machine specs:
- Intel Core i7-6800K
- 64 GB RAM
- Nvidia GTX 1080

**Comment by Tak-Au** [comment] 2017-11-17 06:12
Question what’s the min requirement to run this with one camera?  My laptop has gtx 1060 on i7. I tried to run server and client on the same laptop and I keep getting drop after few sec on the road

**Comment by mesuvash** [comment] 2017-11-18 06:56
Got 3-5 FPS using Titan X Maxwell. Don't know why it's ridiculously slow.

**Comment by benibienz** [comment] 2017-11-21 10:58
I get very low FPS even without a camera and tiny resolution. I think this issue goes beyond UE4's SceneCapture2D. Are there any plans to optimise the performance?

**Comment by nsubiron** [comment] 2017-11-21 11:26
Without cameras we get more than 20 FPS on full-screen (1080GTX). This would be acceptable for most CARLA applications if worked with cameras. Speed optimisation is among our priorities, but we have very limited resources.

**Comment by benibienz** [comment] 2017-11-22 11:58
OK, thanks for your response.

**Comment by WenchaoDing** [comment] 2017-12-01 09:08
Hi,

I find that calling read data at Python client side is very time-consuming when I have multiple cameras. For my setup (6700K + 10800GTX), I typically need 110 ms to read data from 3 cameras, which is the bottleneck. Is there any way to improve the FPS at client side? Such as some parallelism.

**Comment by nsubiron** [comment] 2017-12-01 11:31
Hi @WenchaoDing,

Take into account that the read function waits for the server, if the server is slow this function will wait. We cannot go faster than the server.

Measuring inside the "read_data()" function gives me about 200ms to read the data from the socket + 5ms to process the data. The 200ms is mostly waiting for the server to produce the data.

There is a debugging trick that helps figuring this out, if you disable the synchronous mode, the server will print "Warning: No control received from the client this frame!" every time the client doesn't send the vehicle control on time, meaning the server is faster than the client. If it doesn't print that, then the client is fast enough.

We already considered making this function asynchronous in the client, but that adds quite some complexity to the API while not really speeding it up in most common uses. In case someone needs to parallelise reading the data, she/he will be better off adding this on top of our API to have more control of where to put the parsing of data specific for the case.

**Comment by WenchaoDing** [comment] 2017-12-01 12:42
Hi @nsubiron ,

Thanks for your answer! I got it.

**Comment by tomchen1000** [comment] 2018-02-20 16:54
If the issue is caused by UE4's SceneCapture2D, why Town02 is faster than Town01 (with one camera)?

**Comment by juaxix** [comment] 2018-02-26 11:10
Scenecapture2D is now using the renderqueue ,that, togehter with the settings in the optimization branch (DefaultEngine.ini) you will gain some fps. Also, the problem is to have an optimized scene, we are working on a simple scene to reduce the amount of objects to be rendered.

**Comment by simmates** [comment] 2018-02-28 21:14
I would definitely want to use CARLA, but it gets slow if you add cameras and the suggestion is to remove cameras? This is a simulator for autonomous driving... I'd rather add cameras than remove them.

**Comment by juaxix** [comment] 2018-03-01 10:06
@simmates : It's normal that when you add a camera, any rendering program will slow down a little bit, anyway, we are not saying that you need to remove them, in fact, we are optimizing this together with EPIC team, using the special render code in [ASceneCapture2D](https://docs.unrealengine.com/latest/INT/API/Runtime/Engine/Engine/ASceneCapture2D/index.html) in the render queue of the engine. A lot of new optimizations will come with the new update (0.8.0) ,you can watch the progress [here](https://github.com/carla-simulator/carla/milestones)
Thanks

**Comment by bhairavmehta95** [comment] 2018-03-23 17:02
What is the expected FPS of the Optimizations branch that was just pulled into the master branch? Haven't had a chance to check so I figured someone on this thread might have that answer handy.

**Comment by nsubiron** [comment] 2018-03-23 17:19
We are working on a more detailed benchmark of the speed, but here some preliminary results.

All of these on a GTX1080 on Ubuntu 16.04 on a typical use on Town01 with 20 vehicles and 30 pedestrians.

Scenario      | 0.7.1 (prev. version)  | 0.8.0 Epic mode | 0.8.0 Low mode
--------------|:------:|:---------------:|:---------------:
no cameras    | 22 FPS | 26 FPS          | 60 FPS
one camera    | 9 FPS  | 13 FPS          | 45 FPS
three cameras | 4 FPS  | 6 FPS           | 15 FPS

Still a lot of room for improvement, but definitively much better than previous version :smile:

**Comment by joethompson1961** [comment] 2018-04-13 22:12
What is the difference between Epic and Low Mode?

**Comment by nsubiron** [comment] 2018-04-14 11:56
@joethompson1961 Epic and Low modes refer to the graphics quality of render, you can see an example in this video https://youtu.be/S_XbKHC_hN0?t=1m4s

**Comment by germanros1987** [comment] 2018-05-21 07:56
Should we close this issue?

**Comment by nsubiron** [comment] 2018-05-22 09:59
I guess most of the things here are no longer relevant with the latest improvements. We'll keep opening more issues with specific actions to improve performance.

**Closed by nsubiron** 2018-05-22 09:59 UTC
Labels: question

**Comment by SummerHelen** [comment] 2018-07-17 18:53
How can I check the fps in the simulation process?

**Comment by 0102TH** [comment] 2019-04-15 13:51
Hello!
I met one problem:
Low FPS when I run manual_control_sreeringwheel.py in ubuntu 16.04,and the driving wheel is Logitech G920
system:Ubuntu 16.04
gpu:GTX1060
version:CARLA 0.9.5

Description:
One map of carla is running at other conputer,the Logitech G920 driving force wheel is plugged into my computer ,when I run manual_control_steeringwheel.py,the FPS of Sever and Client is so low that the car's running is not smooth enough.FPS of them is respectively about 16,16.
I am full of confusion.Can anyone give some suggestion?Thanks in advance.

![image](https://user-images.githubusercontent.com/47203090/56138006-8b7f8980-5fc8-11e9-8a18-dcd9e5f8339b.png)

**Comment by soulslicer** [comment] 2019-09-17 16:03
> We are working on a more detailed benchmark of the speed, but here some preliminary results.
> 
> All of these on a GTX1080 on Ubuntu 16.04 on a typical use on Town01 with 20 vehicles and 30 pedestrians.
> 
> Scenario	0.7.1 (prev. version)	0.8.0 Epic mode	0.8.0 Low mode
> no cameras	22 FPS	26 FPS	60 FPS
> one camera	9 FPS	13 FPS	45 FPS
> three cameras	4 FPS	6 FPS	15 FPS
> Still a lot of room for improvement, but definitively much better than previous version

If I have a better GPU will this improve?

**Comment by MasterTigress** [comment] 2021-06-16 16:15
> We are working on a more detailed benchmark of the speed, but here some preliminary results.
> 
> All of these on a GTX1080 on Ubuntu 16.04 on a typical use on Town01 with 20 vehicles and 30 pedestrians.
> 
> Scenario	0.7.1 (prev. version)	0.8.0 Epic mode	0.8.0 Low mode
> no cameras	22 FPS	26 FPS	60 FPS
> one camera	9 FPS	13 FPS	45 FPS
> three cameras	4 FPS	6 FPS	15 FPS
> Still a lot of room for improvement, but definitively much better than previous version 😄

How can I run one camera to achieve 45 FPS, what does no camera mean ? Are there sample code for "one camera" and "no camera"? Can you please share

**Comment by MasterTigress** [comment] 2021-06-16 16:35
I tried a lot to look around for one camera code but couldn't find it. I tried developing one myself but still unable to achieve the fps listed for one camera, can someone please share code of one camera?
