### ISSUE TITLE
The location of a camera attached to the vehicle is inaccurate during the simulation.

### ISSUE THREAD

**Issue by lshmouse** [carla-simulator/carla#6269] opened 2023-03-01 04:12 UTC
- CARLA version:   Carla 0.9.13
- Platform/OS:  Ubuntu 18.04
- Problem you have experienced:
  The location of a camera attached to the vehicle is inaccurate during the simulation.
  ```
        camera_transform = carla.Transform(carla.Location(x=1.5, z=2.4))
        camera = world.spawn_actor(camera_bp, camera_transform, attach_to=vehicle)
  ```
  During each trick, we print the location diff of the vehicle and camera and found that the diff is not equal with `camera_transform` 
  This caused the bounding box of traffic sign is not matched.

  ```
     print("debug: diff: %s" % (vehicle.get_transform().location - camera.get_transform().location))
  ```
  ```
      debug: diff: Vector3D(x=1.500000, y=0.000000, z=-2.400000)
      debug: diff: Vector3D(x=1.493271, y=0.047974, z=-2.403711)
      debug: diff: Vector3D(x=1.493515, y=0.041229, z=-2.403688)
      debug: diff: Vector3D(x=1.500961, y=0.008331, z=-2.399384)
      debug: diff: Vector3D(x=1.501472, y=0.001862, z=-2.399075)
      debug: diff: Vector3D(x=1.500305, y=0.000275, z=-2.399812)
      debug: diff: Vector3D(x=1.500305, y=0.000275, z=-2.399812)
      debug: diff: Vector3D(x=1.501427, y=0.000549, z=-2.399107)
      debug: diff: Vector3D(x=1.501427, y=0.000549, z=-2.399107)
      debug: diff: Vector3D(x=1.501427, y=0.000549, z=-2.399107)
      debug: diff: Vector3D(x=1.501427, y=0.000549, z=-2.399107)
      debug: diff: Vector3D(x=1.501038, y=0.000641, z=-2.399350)
      debug: diff: Vector3D(x=1.501038, y=0.000641, z=-2.399350)
      debug: diff: Vector3D(x=1.501038, y=0.000641, z=-2.399350)
      debug: diff: Vector3D(x=1.499565, y=0.000641, z=-2.400265)
      debug: diff: Vector3D(x=1.499565, y=0.000641, z=-2.400265)
      debug: diff: Vector3D(x=1.499565, y=0.000641, z=-2.400265)
      debug: diff: Vector3D(x=1.501381, y=0.000641, z=-2.399137)
      debug: diff: Vector3D(x=1.501381, y=0.000641, z=-2.399137)
      debug: diff: Vector3D(x=1.501381, y=0.000641, z=-2.399137)
  ```
- What you expected to happen: 
    The camera location will be accurate and stationary to the vehicle location during the simulation.

- Steps to reproduce:
   -  Create a camera and attach it to the vehicle
   -  Run the simulation in sync node in the map: Town01
   - During each trick,  print the location of vehicle and camera.

**Comment by glopezdiest** [comment] 2023-03-03 10:39
You can't just substract the locations of the two actors for that. Due to the camera being attached to the vehicle, the rotation of the vehicle also affects the location of the camera. For example, a camera at 1m above the vehicle will returns a `diff=(0,0,1)` difference, but if the vehicle rolls over, that will now be `diff=(0,0,-1)`, as the camera is below the vehicle.

In this case, the cause of this tiny differences is probably the suspension, and as the changes are very small, it can be confusing (I actually thought you were right the first time reading this), hence why the example is such a drastic one.

Closing this, but feel free to reopen it if you have any more doubts.

**Closed by glopezdiest** 2023-03-03 10:39 UTC
