### ISSUE TITLE
Getting bounding boxes of non actors vehicles

### ISSUE THREAD

**Issue by guygo12345** [carla-simulator/carla#3037] opened 2020-07-07 12:02 UTC
Hey!
I'm training a vehicles detection net and using the bounding boxes of actors as my labels.
I noticed that in some of the maps there are static vehicles which are part of the map. For example - 
![image](https://user-images.githubusercontent.com/25419744/86778014-8b065f00-c062-11ea-9e9c-7ed407d8787b.png)

Those vehicles are not actors, so I can't get their bounding box via the Python API. Is there a way I'm missing to get those bounding boxes?

An illustration of my current code - 
```python
actors = world.get_actors().filter("vehicle*")
for actor in actors:
      save(actor.bounding_box)
```
Thank you!

**Comment by germanros1987** [comment] 2020-07-07 18:43
Duplicate of #2343

**Closed by germanros1987** 2020-07-07 18:43 UTC
