### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by MFaisalZaki** [carla-simulator/carla#176] opened 2018-01-26 18:27 UTC
Hello Sir,

I'm working on building CARLA for MAC OSX but I'm facing this problem regarding downloading some file named content from a google drive, If you may send me a direct download link to be able to download myself then I'll try to automate the whole process soon.

I have attached terminal output when I executed the Update.sh script.
![screen shot 2018-01-26 at 8 23 07 pm](https://user-images.githubusercontent.com/9129265/35454576-42daddf0-02d7-11e8-91e7-12790d19942d.png)

**Comment by MFaisalZaki** [comment] 2018-01-27 08:06
I think this occurs due to google drive permissions, So I have requested an access for this download content. If you may give me this permission, to be able to download the file myself, as for the python script download_from_gdrive.py the token received is always None, which aborts the download.

**Comment by nsubiron** [comment] 2018-01-29 10:19
Hi @MFaisalZaki,

We had some issues with the GDrive storage during Friday and the links went down. That's probably the cause of this. It should be fixed now. Have you tried again? Let us know if you still have issues with this.

**Comment by MFaisalZaki** [comment] 2018-02-02 10:04
I'm have compiled Carla successfully and generated Xcode project files but now I receive this error regarding permission denied for "touch: casetestABC: Permission denied"
<img width="1440" alt="screen shot 2018-02-02 at 12 02 27 pm" src="https://user-images.githubusercontent.com/9129265/35727550-26b154a8-0811-11e8-9691-d3b1918c6151.png">

**Comment by MFaisalZaki** [comment] 2018-02-02 13:26
Fixed the issue was I didn't have write permissions on the UE4 folder since I have installed it using Epic Launcher and didn't compile it.

**Comment by nsubiron** [comment] 2018-02-02 14:02
Great :) thanks for sharing, it seems like it can be a common issue.

**Comment by MFaisalZaki** [comment] 2018-02-02 14:11
Also I have this problem, when I clean Carla it deletes UE4Editor.app 
<img width="747" alt="screen shot 2018-02-02 at 4 10 15 pm" src="https://user-images.githubusercontent.com/9129265/35737307-bf2cbc5a-0833-11e8-80a8-dd46fa8bfdc2.png">

**Comment by MFaisalZaki** [comment] 2018-02-02 18:20
Done. I can run Carla on MAC OS but I can't find ./CarlaUE4.sh to run as a server.

Can you provide me with an example I don't want to download 2.0 GB to check a shell file.

**Comment by MFaisalZaki** [comment] 2018-02-02 18:25
I'm getting missing assets but the simulator is working, how this is possible 
<img width="1440" alt="screen shot 2018-02-02 at 8 24 03 pm" src="https://user-images.githubusercontent.com/9129265/35748577-26e28820-0857-11e8-9067-64aa41b54e8d.png">

**Comment by nsubiron** [comment] 2018-02-03 10:44
There is no _"CarlaUE4.sh"_ script in the source version of CARLA. Once you open the project in the Unreal Editor, you can hit Play to run CARLA.

The missing assets that is complaining about are Unreal's Automotive Materials, follow the instructions in the documentation to [Add Automotive Materials](http://carla.readthedocs.io/en/latest/how_to_add_automotive_materials/).

**Comment by MFaisalZaki** [comment] 2018-02-06 10:03
Here are the modifications for adding support for CARLA on mac os x. Sorry I didn't have time to automate it.
[mac_modifications.zip](https://github.com/carla-simulator/carla/files/1698547/mac_modifications.zip)

**Comment by nsubiron** [comment] 2018-02-06 12:01
Great! thanks for sharing. Do you think you could do a pull-request with the changes?

**Comment by MFaisalZaki** [comment] 2018-02-06 21:08
CARLA simulator is running slow in the editor, I have selected the quality to be low and the material also to be low and still the same issue. It runs at max 5 FPS !!!.

I thought at first it was due to the absence of -pthread flag, but after I added the flag no changes in the performance.

Please note that I'm running on Macbook pro with retina display with 8 cores i7 and 8 GB RAM with SSD disk.

I also received a notification saying since the Xcode installed is not 8.3.x then performance will be degraded, where my xcode version is 9.1

Please advice.

**Comment by nsubiron** [comment] 2018-02-07 09:29
> CARLA is a very performance demanding software, at the very minimum you would
need a computer with a dedicated GPU capable of running Unreal Engine. See
[Unreal Engine's recommended hardware](https://wiki.unrealengine.com/Recommended_Hardware).

CARLA requires a very powerful dedicated GPU to run smoothly. At the moment CARLA has significant performance issues, we are working hard to improve this, but it is something that takes a lot of time and effort.

See also the discussion about performance in #10.

**Comment by MFaisalZaki** [comment] 2018-02-07 13:21
Is it possible to have CARLA like OpenAI Gym environments, but the difference is that CARLA can provide both raw input images, processed input images or any set of states required by the user.

I'm working on motion planning algorithm using machine learning for my masters degree and I was thinking to modify CARLA to provide a set of states which will allow my algorithm to work as expected.

What do you think ?

Also if you can provide a way to remove the attached camera from the vehicle ? if doing so will help in speeding up the FPS ?!

**Closed** 2018-03-07 15:48 UTC

**Comment by amritas02** [comment] 2018-05-18 09:52
Can anyone guide me what to do next? I've built Unreal Engine with Xcode but don't know how to proceed with building Carla!

**Comment by MFaisalZaki** [comment] 2018-05-18 15:38
Merge the changes found in ticke 176 and everything will work.

**Comment by amritas02** [comment] 2018-05-21 19:34
I did all the steps mentioned above. But when I try to open CarlaUE4.uproject with Unreal Engine, it gives me this error. FYI, I have built my Unreal Engine from the source manually. 

<img width="422" alt="screen shot 2018-05-21 at 12 26 30 pm" src="https://user-images.githubusercontent.com/14925965/40326159-36431bcc-5cf3-11e8-9603-da22fe0b4d30.png">

When I say yes to the above, it tries to build the missing files and then says build failed. 

I have been over this so many times - it's not working.

**Comment by Abanoub-G** [comment] 2018-09-29 00:48
> I did all the steps mentioned above. But when I try to open CarlaUE4.uproject with Unreal Engine, it gives me this error. FYI, I have built my Unreal Engine from the source manually.
> 
> <img alt="screen shot 2018-05-21 at 12 26 30 pm" width="422" src="https://user-images.githubusercontent.com/14925965/40326159-36431bcc-5cf3-11e8-9603-da22fe0b4d30.png">
> 
> When I say yes to the above, it tries to build the missing files and then says build failed.
> 
> I have been over this so many times - it's not working.

Hi,
    Did you manage to solve this problem?

**Comment by Abanoub-G** [comment] 2018-09-29 00:59
> Done. I can run Carla on MAC OS but I can't find ./CarlaUE4.sh to run as a server.
> 
> Can you provide me with an example I don't want to download 2.0 GB to check a shell file.

Hey can you please tell me what you exactly did? I have reached to the point where I type on terminal "make launch" and I get this in return:

clang 5.0 is required, but it's not installed.
make sure you build Unreal Engine with clang 5.0 too.
make: *** [setup] Error 1

I already have clang version 7.0.0 installed. I have also installed version 5.0.0 but I don't know how to make my Mac use the 5.0.0 version instead of the 7.0.0 version. Any idea how I can go about this.

Also I don't know how I can use the files you modified below...

> Here are the modifications for adding support for CARLA on mac os x. Sorry I didn't have time to automate it.
> [mac_modifications.zip](https://github.com/carla-simulator/carla/files/1698547/mac_modifications.zip)
> 
> PS: Please check it and if you may integrate it and you can close this issue.

If you can show me how your files can be used that would be awesome. All what I did so far was by following the guide on how to build Carla on windows.

Thanks

**Comment by amritas02** [comment] 2018-10-03 18:43
> > I did all the steps mentioned above. But when I try to open CarlaUE4.uproject with Unreal Engine, it gives me this error. FYI, I have built my Unreal Engine from the source manually.
> > <img alt="screen shot 2018-05-21 at 12 26 30 pm" width="422" src="https://user-images.githubusercontent.com/14925965/40326159-36431bcc-5cf3-11e8-9603-da22fe0b4d30.png">
> > When I say yes to the above, it tries to build the missing files and then says build failed.
> > I have been over this so many times - it's not working.
> 
> Hi,
> Did you manage to solve this problem?

No I didn't. I just stopped using it
