### ISSUE TITLE
Visualization is too bright, and blue

### ISSUE THREAD

**Issue by Leviathan321** [carla-simulator/carla#5278] opened 2022-03-22 14:30 UTC
CARLA version: 0.9.12
Platform/OS: Ubuntu
Problem I  have experienced: Visualization is blinding, everything looks light blueish
What I expected to happen: Visiulatization with normal colours

Other information: I have tried different rendering qualities, different scenarios, but the strange colouring is still there.

![carla](https://user-images.githubusercontent.com/39454752/159505928-fdf31dc1-2dc5-43e2-b5d3-ace7845ffca2.png)

**Comment by TB5zhh** [comment] 2022-03-27 05:02
I have the same issue :(
Did you find any solution?

**Comment by TB5zhh** [comment] 2022-03-27 08:14
found the cause: turns out my GPU driver fails after I turn on Secure Boot. Reinstalling `cuda-drivers` solves my problem

**Comment by Leviathan321** [comment] 2022-03-27 08:24
Ok but I want to run it on my laptop without a dedicated GPU, or is this not possible with the current version?

**Comment by likith3611** [comment] 2022-08-11 06:24
Hii even i am facing the same issue any solution to this? I installed the latest version of carla 0.9.13

**Comment by xqgex** [comment] 2022-10-16 01:36
I gave the exact same problem (Ubuntu 20.04 CARLA 0.9.13). I've tried to reinstall Cuda from [Nvidia website](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu) but that didn't solve the problem.
![Screenshot from 2022-10-15 21-21-56](https://user-images.githubusercontent.com/15404/196013754-de1558f3-3c6d-4dde-8086-ebb4cf553517.png)

**Comment by Hesta256** [comment] 2022-11-17 09:38
I have the exact same problem with Ubuntu 20.04 & CARLA 0.9.13. Reinstalling cuda drivers did not work. Any ideas?

**Comment by bapukokare** [comment] 2023-07-26 14:17
Adjust env parameter 
python ../util/environment.py -rss 1.0 --sun night --fogdist 10000 -si 0 -lg all -ds 0.0 --cloud 0.0 --weather clear  -mss 0.0 --puddles 101.0 -wet 1.0

**Comment by Blyron** [comment] 2024-04-12 10:45
You can run ./Carla.sh with -graphicsadapter=1 and it will use the dedicated Graphics card.
As you have found a solution are you happy to close this issue?

**Comment by Blyron** [comment] 2024-04-19 10:13
Since no response,
I am closing the issue, feel free to reopen

**Closed** 2024-04-26 08:44 UTC

**Comment by Leviathan321** [comment] 2024-04-26 11:33
Sy for my late reply, I could resolve the issue, but I dont know any more how.
