### ISSUE TITLE
Is there a way to record point cloud data with ouput in .pcd format instead of .ply?

### ISSUE THREAD

**Issue by athulg** [carla-simulator/carla#4021] opened 2021-03-25 10:15 UTC
Hello, as the title says, can I record the point cloud data using manual_control.py exported as .pcd files instead of .ply?
I know about [https://github.com/carla-simulator/ros-bridge/blob/master/pcl_recorder/README.md](url) but I'm looking for something in Carla?

Thanks! Any help is appreciated

**Comment by corkyw10** [comment] 2021-03-30 15:46
Duplicate of #4019

**Closed by corkyw10** 2021-03-30 15:46 UTC
