### ISSUE TITLE
Sync Mode; gets stucked in Loop because clients don't tick

### ISSUE THREAD

**Issue by Blyron** [carla-simulator/carla#8407] opened 2024-11-25 10:43 UTC
When you create a camera sensor in sync mode with res of 4k. If you try to save the image to disk or use it in pygame. The client has unknown behaviour in result of not ticking the server again. 

We need to discover what is going on. It happens when you try to save to disk the image or visualize it through pygame.

**Comment by PabloVD** [comment] 2024-12-02 11:22
Log of the above:
```
[2024.12.02-11.20.04:023][ 95]LogBlueprintUserMessages: [CarlaGameMode_C_2147482473] 0
[2024.12.02-11.21.44:452][175]LogCarla: Sensor 1 '' created in primary server
[2024.12.02-11.21.45:111][182]LogTemp: Loaded OpenDrive file '/home/carla/CarlaUnreal/Content/Carla/Maps/OpenDrive/Town10HD_Opt.xodr'
[2024.12.02-11.21.45:775][189]LogTemp: Loaded OpenDrive file '/home/carla/CarlaUnreal/Content/Carla/Maps/OpenDrive/Town10HD_Opt.xodr'
[2024.12.02-11.21.45:816][189]LogCarla: Spawning actor 'sensor.camera.rgb'
[2024.12.02-11.21.45:816][189]LogCarla: Error: ActorAttribute 'color_saturation' is not a color
[2024.12.02-11.21.45:816][189]LogCarla: Error: ActorAttribute 'highlights_gamma' is not a color
[2024.12.02-11.21.45:816][189]g.TimeoutForBlockOnRenderFence = "300000"
[2024.12.02-11.21.45:816][189]LogCarla: Sensor 2 'sensor.camera.rgb' created in primary server
[2024.12.02-11.21.45:818][189]LogCarla: Spawning actor 'vehicle.ue4.mercedes.ccc'
[2024.12.02-11.21.45:822][189]LogCarla: Door name: SM_MercedesCCC_Door_Front_L
[2024.12.02-11.21.45:822][189]LogCarla: Door name: SM_MercedesCCC_Door_Front_R
[2024.12.02-11.21.45:822][189]LogCarla: Spawning actor 'vehicle.ue4.ford.crown'
[2024.12.02-11.21.45:825][189]LogCarla: Door name: Door_FL
[2024.12.02-11.21.45:825][189]LogCarla: Door name: Door_FR
[2024.12.02-11.21.45:825][189]LogCarla: Door name: Door_RL
[2024.12.02-11.21.45:825][189]LogCarla: Door name: Door_RR
[2024.12.02-11.21.45:826][189]LogCarla: Spawning actor 'vehicle.ue4.mercedes.ccc'
[2024.12.02-11.21.45:828][189]LogCarla: Door name: SM_MercedesCCC_Door_Front_L
[2024.12.02-11.21.45:828][189]LogCarla: Door name: SM_MercedesCCC_Door_Front_R
[2024.12.02-11.21.45:829][189]LogCarla: Spawning actor 'vehicle.lincoln.mkz'
[2024.12.02-11.21.45:831][189]LogCarla: Door name: SM_LincolnDoor_Front_L
[2024.12.02-11.21.45:831][189]LogCarla: Door name: SM_LincolnDoor_Front_R
[2024.12.02-11.21.45:831][189]LogCarla: Door name: SM_LincolnDoor_Back_L
[2024.12.02-11.21.45:831][189]LogCarla: Door name: SM_LincolnDoor_Back_R
[2024.12.02-11.21.45:832][189]LogBlueprintUserMessages: [BP_Lincoln2024_C_2147482212] MaterialNotFound
[2024.12.02-11.21.45:832][189]LogCarla: Spawning actor 'vehicle.ue4.chevrolet.impala'
[2024.12.02-11.21.45:834][189]LogCarla: Spawning actor 'vehicle.ue4.bmw.grantourer'
[2024.12.02-11.21.45:836][189]LogCarla: Spawning actor 'vehicle.ue4.mercedes.ccc'
[2024.12.02-11.21.45:838][189]LogCarla: Door name: SM_MercedesCCC_Door_Front_L
[2024.12.02-11.21.45:838][189]LogCarla: Door name: SM_MercedesCCC_Door_Front_R
[2024.12.02-11.21.45:839][189]LogCarla: Spawning actor 'vehicle.firetruck.actors'
[2024.12.02-11.21.45:842][189]LogCarla: Door name: DoorL
[2024.12.02-11.21.45:842][189]LogCarla: Door name: DoorR
[2024.12.02-11.21.45:843][189]LogCarla: Spawning actor 'vehicle.mini.cooper'
[2024.12.02-11.21.45:846][189]LogCarla: Door name: SM_DoorL_Mini2021
[2024.12.02-11.21.45:846][189]LogCarla: Door name: SM_DoorR_Mini2021
[2024.12.02-11.21.45:847][189]LogCarla: Spawning actor 'vehicle.dodge.charger'
[2024.12.02-11.21.45:850][189]LogCarla: Door name: Door_FL
[2024.12.02-11.21.45:850][189]LogCarla: Door name: Door_FR
[2024.12.02-11.21.45:850][189]LogCarla: Door name: Door_RL
[2024.12.02-11.21.45:850][189]LogCarla: Door name: Door_RR
[2024.12.02-11.21.45:852][189]LogCarla: Spawning actor 'vehicle.mini.cooper'
[2024.12.02-11.21.45:854][189]LogCarla: Door name: SM_DoorL_Mini2021
[2024.12.02-11.21.45:854][189]LogCarla: Door name: SM_DoorR_Mini2021
[2024.12.02-11.21.45:854][189]LogCarla: Spawning actor 'vehicle.ue4.ford.mustang'
[2024.12.02-11.21.45:856][189]LogCarla: Spawning actor 'vehicle.nissan.patrol'
[2024.12.02-11.21.45:860][189]LogCarla: Door name: SM_DoorL_Patrol2021
[2024.12.02-11.21.45:860][189]LogCarla: Door name: SM_DoorR_Patrol2021
[2024.12.02-11.21.45:860][189]LogCarla: Door name: SM_DoorRL_Patrol2021
[2024.12.02-11.21.45:860][189]LogCarla: Door name: SM_DoorRR_Patrol2021
[2024.12.02-11.21.45:861][189]LogCarla: Spawning actor 'vehicle.taxi.ford'
[2024.12.02-11.21.45:864][189]LogCarla: Door name: Door_FL
[2024.12.02-11.21.45:864][189]LogCarla: Door name: Door_FR
[2024.12.02-11.21.45:864][189]LogCarla: Door name: Door_RL
[2024.12.02-11.21.45:864][189]LogCarla: Door name: Door_RR
[2024.12.02-11.21.45:865][189]LogCarla: Spawning actor 'vehicle.dodgecop.charger'
[2024.12.02-11.21.45:869][189]LogCarla: Door name: Door_FL
[2024.12.02-11.21.45:869][189]LogCarla: Door name: Door_FR
[2024.12.02-11.21.45:869][189]LogCarla: Door name: Door_RL
[2024.12.02-11.21.45:869][189]LogCarla: Door name: Door_RR
[2024.12.02-11.21.45:871][189]LogBlueprintUserMessages: [BP_ChargerCop2024_C_2147482063] MaterialNotFound
[2024.12.02-11.21.45:871][189]LogBlueprintUserMessages: [BP_ChargerCop2024_C_2147482063] MaterialNotFound
[2024.12.02-11.21.45:871][189]LogCarla: Spawning actor 'vehicle.ue4.ford.mustang'
[2024.12.02-11.21.45:873][189]LogCarla: Spawning actor 'vehicle.ue4.ford.mustang'
[2024.12.02-11.21.45:875][189]LogCarla: Spawning actor 'vehicle.ue4.chevrolet.impala'
[2024.12.02-11.21.45:877][189]LogCarla: Spawning actor 'vehicle.taxi.ford'
[2024.12.02-11.21.45:880][189]LogCarla: Door name: Door_FL
[2024.12.02-11.21.45:880][189]LogCarla: Door name: Door_FR
[2024.12.02-11.21.45:880][189]LogCarla: Door name: Door_RL
[2024.12.02-11.21.45:880][189]LogCarla: Door name: Door_RR
[2024.12.02-11.21.45:881][189]LogCarla: Spawning actor 'vehicle.ue4.ford.mustang'
[2024.12.02-11.21.45:883][189]LogCarla: Spawning actor 'vehicle.ue4.ford.mustang'
[2024.12.02-11.21.45:885][189]LogCarla: Spawning actor 'vehicle.ue4.mercedes.ccc'
[2024.12.02-11.21.45:887][189]LogCarla: Door name: SM_MercedesCCC_Door_Front_L
[2024.12.02-11.21.45:887][189]LogCarla: Door name: SM_MercedesCCC_Door_Front_R
[2024.12.02-11.21.45:888][189]LogCarla: Spawning actor 'vehicle.ue4.ford.crown'
[2024.12.02-11.21.45:891][189]LogCarla: Door name: Door_FL
[2024.12.02-11.21.45:891][189]LogCarla: Door name: Door_FR
[2024.12.02-11.21.45:891][189]LogCarla: Door name: Door_RL
[2024.12.02-11.21.45:891][189]LogCarla: Door name: Door_RR
[2024.12.02-11.21.45:892][189]LogCarla: Spawning actor 'vehicle.carlacola.actors'
[2024.12.02-11.21.45:895][189]LogCarla: Door name: DoorL
[2024.12.02-11.21.45:895][189]LogCarla: Door name: DoorR
[2024.12.02-11.21.45:895][189]LogCarla: Spawning actor 'vehicle.ambulance.ford'
[2024.12.02-11.21.45:899][189]LogCarla: Door name: DoorL
[2024.12.02-11.21.45:899][189]LogCarla: Door name: DoorR
[2024.12.02-11.21.45:900][189]LogCarla: Spawning actor 'vehicle.ue4.audi.tt'
[2024.12.02-11.21.45:902][189]LogCarla: Spawning actor 'vehicle.dodgecop.charger'
[2024.12.02-11.21.45:906][189]LogCarla: Door name: Door_FL
[2024.12.02-11.21.45:906][189]LogCarla: Door name: Door_FR
[2024.12.02-11.21.45:906][189]LogCarla: Door name: Door_RL
[2024.12.02-11.21.45:906][189]LogCarla: Door name: Door_RR
[2024.12.02-11.21.45:907][189]LogBlueprintUserMessages: [BP_ChargerCop2024_C_2147481907] MaterialNotFound
[2024.12.02-11.21.45:907][189]LogBlueprintUserMessages: [BP_ChargerCop2024_C_2147481907] MaterialNotFound
[2024.12.02-11.21.45:907][189]LogCarla: Spawning actor 'vehicle.mini.cooper'
[2024.12.02-11.21.45:910][189]LogCarla: Door name: SM_DoorL_Mini2021
[2024.12.02-11.21.45:910][189]LogCarla: Door name: SM_DoorR_Mini2021
[2024.12.02-11.21.45:910][189]LogCarla: Spawning actor 'vehicle.nissan.patrol'
[2024.12.02-11.21.45:913][189]LogCarla: Door name: SM_DoorL_Patrol2021
[2024.12.02-11.21.45:913][189]LogCarla: Door name: SM_DoorR_Patrol2021
[2024.12.02-11.21.45:913][189]LogCarla: Door name: SM_DoorRL_Patrol2021
[2024.12.02-11.21.45:913][189]LogCarla: Door name: SM_DoorRR_Patrol2021
[2024.12.02-11.21.45:914][189]LogCarla: Spawning actor 'vehicle.ue4.ford.crown'
[2024.12.02-11.21.45:917][189]LogCarla: Door name: Door_FL
[2024.12.02-11.21.45:917][189]LogCarla: Door name: Door_FR
[2024.12.02-11.21.45:917][189]LogCarla: Door name: Door_RL
[2024.12.02-11.21.45:917][189]LogCarla: Door name: Door_RR
[2024.12.02-11.21.46:682][189]LogPSOHitching: Encountered 300 PSO creation hitches so far (75 graphics, 225 compute). 46 of them were precached.
Ensure condition failed: (ExpectedSrcLayout == VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL) [File:./Runtime/VulkanRHI/Private/VulkanTexture.cpp] [Line: 2515] 
Expected source texture to be in VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, actual layout is VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
[2024.12.02-11.21.49:136][189]LogCore: 0x0000000011d7b0b8 Dladdr: 0.536292ms Open: 0.017622ms Search: 0.055504ms
[2024.12.02-11.21.49:136][189]LogCore: 0x000000000a9bcead Dladdr: 0.567130ms Open: 0.007363ms Search: 0.050354ms
[2024.12.02-11.21.49:137][189]LogCore: 0x0000000009dbfea5 Dladdr: 0.554195ms Open: 0.006252ms Search: 0.045475ms
[2024.12.02-11.21.49:137][189]LogCore: 0x000000000aaca9ae Dladdr: 0.548424ms Open: 0.007064ms Search: 0.046246ms
[2024.12.02-11.21.49:138][189]LogCore: 0x000000000aacc860 Dladdr: 0.546602ms Open: 0.006812ms Search: 0.050605ms
[2024.12.02-11.21.49:139][189]LogCore: 0x000000000aafd6a1 Dladdr: 0.544127ms Open: 0.006692ms Search: 0.051887ms
[2024.12.02-11.21.49:139][189]LogCore: 0x000000000aacb514 Dladdr: 0.555087ms Open: 0.007153ms Search: 0.044403ms
[2024.12.02-11.21.49:140][189]LogCore: 0x00000000067a1db1 Dladdr: 0.568502ms Open: 0.007033ms Search: 0.053350ms
[2024.12.02-11.21.49:141][189]LogCore: 0x000000000628f1ea Dladdr: 0.568533ms Open: 0.007584ms Search: 0.052137ms
[2024.12.02-11.21.49:141][189]LogCore: 0x000000000628e2fc Dladdr: 0.563032ms Open: 0.006903ms Search: 0.049843ms
[2024.12.02-11.21.49:142][189]LogCore: 0x000000000628d50e Dladdr: 0.560407ms Open: 0.006402ms Search: 0.044393ms
[2024.12.02-11.21.49:143][189]LogCore: 0x000000000abe38d4 Dladdr: 0.548675ms Open: 0.006492ms Search: 0.054222ms
[2024.12.02-11.21.49:143][189]LogCore: 0x00000000063fe512 Dladdr: 0.571427ms Open: 0.006663ms Search: 0.050644ms
[2024.12.02-11.21.49:144][189]LogCore: 0x0000000006372720 Dladdr: 0.577840ms Open: 0.006863ms Search: 0.052468ms
[2024.12.02-11.21.49:144][189]LogCore: 0x00007fa9a84b0ac2 Dladdr: 0.017383ms Open: 0.009007ms Search: 0.000681ms
[2024.12.02-11.21.49:144][189]LogCore: 0x00007fa9a8541a03 Dladdr: 0.023143ms Open: 0.008155ms Search: 0.000190ms
[2024.12.02-11.21.49:144][189]LogStats: FPlatformStackWalk::StackWalkAndDump -  0.009 s
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: === Handled ensure: ===
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: 
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: Ensure condition failed: (ExpectedSrcLayout == VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL)  [File:./Runtime/VulkanRHI/Private/VulkanTexture.cpp] [Line: 2515] 
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: Expected source texture to be in VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, actual layout is VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: Stack: 
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: [Callstack] 0x0000000011d7b0b9 CarlaUnreal!FVulkanCommandListContext::RHICopyTexture(FRHITexture*, FRHITexture*, FRHICopyTextureInfo const&)::$_0::operator()() const [/home/glopez/UnrealEngine5_carla/Engine/Source/./Runtime/VulkanRHI/Private/VulkanTexture.cpp:2515]
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: [Callstack] 0x000000000a9bceae CarlaUnreal!FVulkanCommandListContext::RHICopyTexture(FRHITexture*, FRHITexture*, FRHICopyTextureInfo const&) [/home/glopez/UnrealEngine5_carla/Engine/Source/./Runtime/VulkanRHI/Private/VulkanTexture.cpp:2515]
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: [Callstack] 0x0000000009dbfea6 CarlaUnreal!FRHICommand<FRHICommandCopyTexture, FRHICommandCopyTextureString2152>::ExecuteAndDestruct(FRHICommandListBase&) [/home/glopez/UnrealEngine5_carla/Engine/Source/Runtime/RHI/Public/RHICommandList.h:1471]
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: [Callstack] 0x000000000aaca9af CarlaUnreal!FRHICommandListBase::Execute() [/home/glopez/UnrealEngine5_carla/Engine/Source/./Runtime/RHI/Private/RHICommandList.cpp:429]
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: [Callstack] 0x000000000aacc861 CarlaUnreal!FRHICommandListExecutor::FTranslateState::Translate(FRHICommandListBase*) [/home/glopez/UnrealEngine5_carla/Engine/Source/./Runtime/RHI/Private/RHICommandList.cpp:902]
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: [Callstack] 0x000000000aafd6a2 CarlaUnreal!UE::Core::Private::Function::TFunctionRefCaller<FRHICommandListExecutor::FSubmitState::Dispatch(FRHICommandListBase*)::$_0, void>::Call(void*) [/home/glopez/UnrealEngine5_carla/Engine/Source/./Runtime/RHI/Private/RHICommandList.cpp:871]
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: [Callstack] 0x000000000aacb515 CarlaUnreal!FRHICommandListExecutor::FTaskPipe::Execute(FRHICommandListExecutor::FTaskPipe::FTask*, TRefCountPtr<FBaseGraphTask> const&) const [/home/glopez/UnrealEngine5_carla/Engine/Source/Runtime/Core/Public/Templates/Function.h:470]
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: [Callstack] 0x00000000067a1db2 CarlaUnreal!TGraphTask<TFunctionGraphTaskImpl<void (ENamedThreads::Type, TRefCountPtr<FBaseGraphTask> const&), (ESubsequentsMode::Type)0> >::ExecuteTask() [/home/glopez/UnrealEngine5_carla/Engine/Source/Runtime/Core/Public/Templates/Function.h:470]
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: [Callstack] 0x000000000628f1eb CarlaUnreal!UE::Tasks::Private::FTaskBase::TryExecuteTask() [/home/glopez/UnrealEngine5_carla/Engine/Source/Runtime/Core/Public/Tasks/TaskPrivate.h:504]
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: [Callstack] 0x000000000628e2fd CarlaUnreal!FNamedTaskThread::ProcessTasksNamedThread(int, bool) [/home/glopez/UnrealEngine5_carla/Engine/Source/Runtime/Core/Public/Async/TaskGraphInterfaces.h:482]
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: [Callstack] 0x000000000628d50f CarlaUnreal!FNamedTaskThread::ProcessTasksUntilQuit(int) [/home/glopez/UnrealEngine5_carla/Engine/Source/./Runtime/Core/Private/Async/TaskGraph.cpp:667]
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: [Callstack] 0x000000000abe38d5 CarlaUnreal!FRHIThread::Run() [/home/glopez/UnrealEngine5_carla/Engine/Source/./Runtime/RenderCore/Private/RenderingThread.cpp:269]
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: [Callstack] 0x00000000063fe513 CarlaUnreal!FRunnableThreadPThread::Run() [/home/glopez/UnrealEngine5_carla/Engine/Source/./Runtime/Core/Private/HAL/PThreadRunnableThread.cpp:25]
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: [Callstack] 0x0000000006372721 CarlaUnreal!FRunnableThreadPThread::_ThreadProc(void*) [/home/glopez/UnrealEngine5_carla/Engine/Source/Runtime/Core/Private/HAL/PThreadRunnableThread.h:187]
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: [Callstack] 0x00007fa9a84b0ac3 libc.so.6!UnknownFunction(0x94ac2)
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: [Callstack] 0x00007fa9a8541a04 libc.so.6!clone(+0x43)
[2024.12.02-11.21.49:144][189]LogOutputDevice: Error: 
[2024.12.02-11.21.49:154][189]LogStats:                SubmitErrorReport -  0.000 s
[2024.12.02-11.21.49:170][189]LogStats:                    SendNewReport -  0.017 s
[2024.12.02-11.21.49:170][189]LogStats:             FDebug::EnsureFailed -  0.036 s
[2024.12.02-11.21.49:471][190]LogCarla: Spawning actor 'walker.pedestrian.0033'
[2024.12.02-11.21.49:473][190]LogCarla: Spawning actor 'walker.pedestrian.0042'
[2024.12.02-11.21.49:477][190]LogCarla: Spawning actor 'walker.pedestrian.0038'
[2024.12.02-11.21.49:478][190]LogCarla: Spawning actor 'walker.pedestrian.0039'
[2024.12.02-11.21.49:480][190]LogCarla: Spawning actor 'walker.pedestrian.0039'
[2024.12.02-11.21.49:480][190]LogCarla: Spawning actor 'walker.pedestrian.0018'
[2024.12.02-11.21.49:481][190]LogCarla: Spawning actor 'walker.pedestrian.0026'
[2024.12.02-11.21.49:482][190]LogCarla: Spawning actor 'walker.pedestrian.0051'
[2024.12.02-11.21.49:484][190]LogCarla: Spawning actor 'walker.pedestrian.0033'
[2024.12.02-11.21.49:485][190]LogCarla: Spawning actor 'walker.pedestrian.0040'
[2024.12.02-11.21.50:496][191]LogCarla: Spawning actor 'controller.ai.walker'
[2024.12.02-11.21.50:496][191]LogCarla: Spawning actor 'controller.ai.walker'
[2024.12.02-11.21.50:496][191]LogCarla: Spawning actor 'controller.ai.walker'
[2024.12.02-11.21.50:496][191]LogCarla: Spawning actor 'controller.ai.walker'
[2024.12.02-11.21.50:497][191]LogCarla: Spawning actor 'controller.ai.walker'
[2024.12.02-11.21.50:497][191]LogCarla: Spawning actor 'controller.ai.walker'
[2024.12.02-11.21.50:497][191]LogCarla: Spawning actor 'controller.ai.walker'
[2024.12.02-11.21.50:497][191]LogCarla: Spawning actor 'controller.ai.walker'
[2024.12.02-11.21.50:497][191]LogCarla: Spawning actor 'controller.ai.walker'
[2024.12.02-11.21.50:497][191]LogCarla: Spawning actor 'controller.ai.walker'
```

**Comment by PabloVD** [comment] 2024-12-02 11:27
This problem does not appear if:

- the same script runs in asynchronous mode (with the `asynch` flag)
- the camera is of lower resolution (e.g. 1080p)

**Comment by PabloVD** [comment] 2024-12-02 12:06
Some updates:

- Removing the `camera.listen` line in the snippet above the script works as expected and the server does not get stuck. Thus, the problem may be related to the library saving images to disk or moving them to the pygame screen, which in principle are boost::gil and libpng.
- I could not reproduce the issue with a manual control in synch with 4k resolution (in neither editor nor a package).
- Note that this is not a crash, the server just gets stuck. For instance, if afterwards we set it in asynchronous with other script, the server keeps running as usual:

```python
settings = world.get_settings()
settings.synchronous_mode = False
world.apply_settings(settings)
```

**Comment by PabloVD** [comment] 2024-12-05 09:46
Issue no reproducible in all systems. It can be fixed increasing the timeout in `client.set_timeout(1000.0)`.

**Closed by PabloVD** 2024-12-05 09:46 UTC
Labels: ue5-bugs, ue5-critical-issues
