### ISSUE TITLE
Waypoints not positioned at the centre of lanes

### ISSUE THREAD

**Issue by pravinblaze** [carla-simulator/carla#1349] opened 2019-03-07 11:48 UTC
There seems to be a problem in how the waypoints are positioned on the lane in some road segments.
This is causes problems while trying to localise actor positions relative to the lane centre since the waypoints are not always at the visible centre of lanes.

**Comment by marcgpuig** [comment] 2019-03-12 13:17
@pravinblaze 
Is this in Town03?

**Comment by nishanthjois** [comment] 2019-03-18 13:40
Yes, it is in Town03.

**Comment by nishanthjois** [comment] 2019-03-29 11:55
Any update on this?

**Comment by akki6843** [comment] 2019-04-01 07:11
Closing this as the issue is fixed with latest build, spawning of props is now correct (i.e. on Sidewalk) in Town03 and Town05.
Here is the screenshot of vending machine spawning on the sidewalk.
![Screenshot from 2019-04-01 12-30-55](https://user-images.githubusercontent.com/16385631/55309433-67c22c80-547b-11e9-96b9-3d5f464cf071.png)

**Closed by akki6843** 2019-04-01 07:11 UTC
Labels: bug
