### ISSUE TITLE
Offset in big vehicle Bounding Boxes position

### ISSUE THREAD

**Issue by AitorIglesias** [carla-simulator/carla#7089] opened 2024-01-24 09:08 UTC
CARLA version: 9.14
Platform/OS: Linux
Problem you have experienced: There is an offset in the position of the bounding box of big vehicles.

I am currently working to generate auto-labeled data. I generate point clouds, images and bounding boxes. I get the bounding boxes for each actor and I noticed that the bounding box for large vehicles like trucks or buses does not perfectly match the object in the point cloud. It can be seen in these images:

![imagen](https://github.com/carla-simulator/carla/assets/61094941/1852a0be-a545-4969-b175-15d147b6b5b5)
![imagen](https://github.com/carla-simulator/carla/assets/61094941/a4359b2d-8ba3-40c6-85e1-3f7ea92c214c)

I know it is not the code because this does not happen with other actors or environment objects, as you can see in the example:

![imagen](https://github.com/carla-simulator/carla/assets/61094941/96a6e4eb-068a-4032-b726-ca2f32c8f0d0)
![imagen](https://github.com/carla-simulator/carla/assets/61094941/290a184f-ff8a-4ff6-9f22-92db34db81c6)

**Comment by yyxssm** [comment] 2024-01-26 13:11
Same question to me, how to solve it?

**Comment by gsmario** [comment] 2024-05-17 11:21
Hi, I had a look at the bus, and you're right, but there is a reason:
If you look at this image, you can see how the left mirror is creating that offset, since the right mirror is not in the same position as the left. So when creating the bounding box, unreal is adding that extra size to the left side of the bus.
The bounding box is working as intended.
![bus](https://github.com/carla-simulator/carla/assets/44405709/24bc8f89-fb56-4780-b6d3-ddd85e59d1eb)

**Comment by gsmario** [comment] 2024-05-17 11:49
I've also checked the other big vehicles, and as you can see, their bounding box is correct, so, which ones do you mean are wrong, besides the bus?
![trucks](https://github.com/carla-simulator/carla/assets/44405709/0fd2cd40-e048-4b20-9cd0-61d07773a932)

**Comment by gsmario** [comment] 2024-05-24 11:01
I'm closing the issue, since the problem seems solved.
Thanks for your time.

**Closed by gsmario** 2024-05-24 11:01 UTC
Labels: art
