### ISSUE TITLE
Issue with Xerces library in OSM2ODR build using make PythonAPI

### ISSUE THREAD

**Issue by Huzefa-Kagalwala** [carla-simulator/carla#5485] opened 2022-06-01 17:26 UTC
Hello,

I am unable to run `make PythonAPI` sucessfully. 
CARLA version: 0.9.13
Platform: Windows 10
Python: 3.7.9 (64-bit)

I built the modified version of UE 4.26 as mentioned here: https://carla.readthedocs.io/en/latest/build_windows/.
When I try to run the `make PythonAPI` command, it installs all the libraries successfully but at the end it fails due to some linking errors with the Xerces library. I commented out the other installations in `Setup.bat` and re-installed Xerces but to no avail. I even deleted the `Build` folder, ran `make clean` and re-ran the `make PythonAPI` command. But nothing solves the issues, I always end up at this message.

Any help is appreciated.

![image](https://user-images.githubusercontent.com/60194983/171465735-7ce509db-c01c-423b-a95e-f44dd9749310.png)

**Comment by kanpachi1** [comment] 2022-06-08 01:51
Running `make PythonAPI` twice like https://github.com/carla-simulator/carla/issues/4525#issuecomment-911223426 said worked for me.

**Comment by Blyron** [comment] 2024-05-10 08:31
Have this solved your issue? Are you happy to close this. 
This is fixed in dev version of CARLA. The issue is related with git downloads

**Closed** 2024-05-24 08:13 UTC
