### ISSUE TITLE
undefined symbol: PyString_Type

### ISSUE THREAD

**Issue by zwbai** [carla-simulator/carla#1762] opened 2019-06-17 20:25 UTC
after the installation, I want to run the tutorial.py to test the environment. But here is the problem:
![PyString](https://user-images.githubusercontent.com/23632221/59634198-0ec17680-9103-11e9-8f2c-dbb7e3072ded.png)
I also find that the problem is whenever I import Carla in python, this problem will occur. is anyone knows why?

**Comment by sabhiram** [comment] 2019-06-19 06:17
Isn't this a duplicate of : https://github.com/carla-simulator/carla/issues/1765?

**Closed** 2019-06-20 23:25 UTC

**Comment by havefun28** [comment] 2019-06-29 15:30
Hi! Have you solved it? If so, how?

**Comment by sound-design** [comment] 2020-01-30 04:48
Yes it is a duplicate of an issue that is still as of January 29th still unsolved.

**Comment by revikiran1991** [comment] 2020-02-11 18:48
Same here. I am also facing this issue fro a long time. specially when I make own carla
